//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumas_Stok_Takip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KumasStokDBEntities : DbContext
    {
        public KumasStokDBEntities()
            : base("name=KumasStokDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Desen> Desenler { get; set; }
        public virtual DbSet<Kategori> Kategoriler { get; set; }
        public virtual DbSet<Ozellik> Ozellikler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tur> Turler { get; set; }
        public virtual DbSet<Urun> Urunler { get; set; }
        public virtual DbSet<YikamaBilgi> YikamaBilgileri { get; set; }
        public virtual DbSet<GirisBilgi> GirisBilgileri { get; set; }
        public virtual DbSet<Fatura> Faturalar { get; set; }
        public virtual DbSet<FaturaDetay> FaturaDetaylari { get; set; }
        public virtual DbSet<Firma> Firmalar { get; set; }
    }
}
