//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumas_Stok_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaDetay
    {
        public int id { get; set; }
        public int urunID { get; set; }
        public int adet { get; set; }
        public double toplamFiyat { get; set; }
        public int faturaID { get; set; }
    
        public virtual Fatura Faturalar { get; set; }
        public virtual Urun Urunler { get; set; }
    }
}
