//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumas_Stok_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.FaturaDetaylari = new HashSet<FaturaDetay>();
        }
    
        public int ID { get; set; }
        public double genelToplam { get; set; }
        public System.DateTime tarih { get; set; }
        public int firmaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaDetay> FaturaDetaylari { get; set; }
        public virtual Firma Firmalar { get; set; }
    }
}
