//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumas_Stok_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisBilgi
    {
        public int ID { get; set; }
        public string Kullanici { get; set; }
        public string Sifre { get; set; }
        public bool Hatirla { get; set; }
    }
}
