//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumas_Stok_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ozellik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ozellik()
        {
            this.Urunler = new HashSet<Urun>();
        }
    
        public int ID { get; set; }
        public Nullable<int> desenID { get; set; }
        public Nullable<int> turID1 { get; set; }
        public Nullable<int> oran1 { get; set; }
        public Nullable<int> turID2 { get; set; }
        public Nullable<int> oran2 { get; set; }
        public Nullable<int> turID3 { get; set; }
        public Nullable<int> oran3 { get; set; }
    
        public virtual Desen Desenler { get; set; }
        public virtual Tur Turler { get; set; }
        public virtual Tur Turler1 { get; set; }
        public virtual Tur Turler2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun> Urunler { get; set; }
    }
}
