//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumas_Stok_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.FaturaDetaylari = new HashSet<FaturaDetay>();
        }
    
        public int ID { get; set; }
        public string ad { get; set; }
        public Nullable<double> fiyat { get; set; }
        public Nullable<int> metre { get; set; }
        public Nullable<int> genislik { get; set; }
        public Nullable<double> agirlik { get; set; }
        public string renk { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<int> yikamaID { get; set; }
        public Nullable<int> ozellikID { get; set; }
    
        public virtual Ozellik Ozellikler { get; set; }
        public virtual YikamaBilgi YikamaBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaDetay> FaturaDetaylari { get; set; }
    }
}
