//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kumas_Stok_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class YikamaBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YikamaBilgi()
        {
            this.Urunler = new HashSet<Urun>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> makine { get; set; }
        public Nullable<bool> kuruTemizleme { get; set; }
        public Nullable<bool> kurutucu { get; set; }
        public Nullable<bool> camasirSuyu { get; set; }
        public Nullable<int> derece { get; set; }
        public Nullable<int> cekmePayi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun> Urunler { get; set; }
    }
}
